pipeline:
  build-py2:
    image: alpine
    commands:
      - apk --no-cache add python py-pip gcc python-dev musl-dev
      - pip install -e .[testing]
      - pytest

  build-py3:
    image: alpine
    commands:
      - apk --no-cache add python3 gcc python3-dev musl-dev
      - pip3 install -e .[testing]
      - pytest

  slack:
    image: plugins/slack
    channel: bots
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
