pipeline:
  build-py2:
    image: debian:stretch
    commands:
      - apt update && apt upgrade -y && apt install -y build-essential python-dev python-pip
      - pip install -e .[testing]
      - pytest

  build-py3:
    image: debian:stretch
    commands:
      - apt update && apt upgrade -y && apt install -y build-essential python3-dev python3-pip
      - pip3 install -e .[testing]
      - pytest

  slack:
    image: plugins/slack
    channel: bots
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
      event: push
