pipeline:
  build:
    image: alpine
    commands:
      - apk --no-cache add python python3 gcc python-dev python3-dev musl-dev
      - pip3 install tox
      - tox

  slack:
    image: plugins/slack
    channel: bots
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
